import { Inter } from 'next/font/google'
import Provider from './components/Authprovider/Provider'
import 'bootstrap/dist/css/bootstrap.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextJs App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {children}   
        </Provider>      
        </body>
    </html>
  )
}
